version: 2.1
 
orbs:
  ruby: circleci/ruby@2.0.1
 
jobs:
  hello-world:
    docker:
      - image: cimg/ruby:3.2.4-node
    steps:
      - checkout
      - run:
          name: Print Hello World
          command: echo "Hello, World!"
 
  build-docker-image:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-image-name:your-tag .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push your-image-name:your-tag
 
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy Application
          command: echo "Deploying the application..."
 
workflows:
  build-and-deploy:
    jobs:
      - hello-world
      - build-docker-image:
          requires:
            - hello-world
      - deploy:
          requires:
            - build-docker-image