version: 2.1
 
orbs:
  ruby: circleci/ruby@2.0.1
 
jobs:
  hello-world:
    docker:
      - image: cimg/ruby:3.2.4-node
    steps:
      - checkout
      - run:
          name: Print Hello World
          command: echo "Hello, World!"
 
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy Application
          command: echo "Deploying the application..."
 
workflows:
  build-and-deploy:
    jobs:
      - hello-world
      - deploy:
          requires:
            - hello-world